import Layout from '../sections/Layout'
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Layout>
        <section className="flex flex-col justify-center items-center space-y-10 mt-12 sm:mt-6 md:mt-8">
          <h1 className="text-3xl text-gray-800 text-center leading-normal font-bold capitalize dark:text-gray-100">Building applications for Web3 democratization</h1>
          <p className="text-xl sm:text-md text-center text-gray-500 dark:text-gray-200">We help for onboarding of new comers</p>
          <Image className="flex-shrink-0"
            src="/logo_IL.png"
            alt="Logo"
            width={120}
            height={120}
          />
          <hr />
          <h1 className="text-2xl text-gray-800 text-center leading-normal font-bold dark:text-gray-100">What we &apos;ve built</h1>
          <div className="bg-slate-100 border border-gray-300 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700">
            <a href="https://interpool.app" target="_blank" rel="noreferrer">
              <Image className="flex-shrink-0 mt-2 mx-auto"
                src="/logo_interpool.png"
                alt="interpool_logo"
                width={150}
                height={150}
              />
              <h5 className="ml-2 mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">interpool.app</h5>
            </a>
            <p className="ml-1 mb-3 font-normal text-gray-700 dark:text-gray-400">A Sport Prediction Game with no losers, where the winners share the interests generated by the deposits of all the participants</p>
            <strong className="ml-1">Winner of:</strong>
            <div className="flex items-stretch mt-2 ml-1 mb-2">
              <Image
                src="/tron-trx-logo.png"
                alt="tron_logo"
                width={20}
                height={20}
              />
              <p className="ml-1">TRON DAO Forum: 🥇 Ecosystem 1st Place</p>
            </div>
            <div className="flex items-stretch ml-1 mb-3">
              <Image
                src="/tron-trx-logo.png"
                alt="tron_logo"
                width={20}
                height={20}
              />
              <p className="ml-1">Ecosystem Technical 5th Place</p>
            </div>
          </div>

          <div className="bg-slate-100 border border-gray-300 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700">
            <a href="https://nopoolnogame.xyz" target="_blank" rel="noreferrer">
              <Image className="flex-shrink-0 mt-2 mx-auto"
                src="/logo_npng.png"
                alt="npng_logo"
                width={150}
                height={150}
              />
              <h5 className="ml-2 mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">nopoolnogame.xyz</h5>
            </a>
            <p className="ml-1 mb-3 font-normal text-gray-700 dark:text-gray-400">A GameFi with no losers, where the winners share the interests generated by the deposits of all the participants</p>
            <strong className="ml-1">Winner of:</strong>
            <div className="flex items-stretch mt-2 ml-1 mb-2">
              <Image
                src="/aave-logo.png"
                alt="aave_logo"
                width={20}
                height={20}
                max-height={20}

              />
              <p className="ml-1">AAVE Grants DAO — 🥇 Stablecoin Growth 1st Place</p>
            </div>
            <div className="flex items-stretch mt-2 ml-1 mb-2">
              <Image
                src="/optimism.svg"
                alt="optimism_logo"
                width={20}
                height={20}
                max-height={20}

              />
              <p className="ml-1">Optimism — 🥇 Best Optimism Game 1st Place</p>
            </div>
            <div className="flex items-stretch mt-2 ml-1 mb-2">
              <Image
                src="/optimism.svg"
                alt="optimism_logo"
                width={20}
                height={20}
                max-height={20}
              />
              <p className="ml-1">Optimism — Top 🔟 projects</p>
            </div>
          </div>

        </section>
      </Layout>
    </>
  )
}
