import Link from "next/link";

const Interpool = () => (
    <>
        <h1 className="text-center font-semibold text-[40px] mt-28 mb-10 ">InterPool</h1>
        <p className="text-center my-10">A Sport Prediction Game with no loosers, where the winners share the interests generated by the deposits of all the participants. </p>
        <p className="text-center my-10">Page in Construction</p>
        <Link className="text-white underline ml-24 my-10" href="https://interpool.app">InterPool Website</Link><br /><br /><br />
    </>
)

export default Interpool;