import Link from "next/link";
import Image from 'next/image';

const Interpool = () => (
    <>
        <div className="flex justify-center items-center">
        <div>
        <h1 className="text-center font-semibold text-[50px]  mt-10 ">InterPool</h1>        
        </div>
        <Link href="https://interpool.app" target="_blank" rel="noopener noreferrer" className="opacity-80 hover:opacity-100">
        <div className="mx-10">
            <Image
            src="/link.svg"
            alt="Website"
            width={50}
            height={50}
          />   
        </div>        
        </Link>
        </div>
        <p className="text-justify text-[25px] mt-10 px-10 md:px-44"> A <span className="font-extrabold">Sport Prediction Game with no loser</span>, where the <span className="font-extrabold">winners share the interests generated by the deposits</span> of all the participants. <br /><br />You can <span className="font-extrabold">earn money without taking the risk of losing any.</span><br /><br /></p>
         
        <h2 className="text-center font-semibold text-[30px]  mt-10 mb-10">Problems we address</h2>
        
        <ul className="text-justify mt-10 px-10 md:px-44 list-disc list-inside">
        <li>Gamblers waste so much money (that they sometimes don’t have) on gambling games.</li><br />
        <li>Difficulties to onboard newcomers in the Blockchain ecosystem that is too complex, and not really sexy for most humans.</li>
        </ul>
        <h2 className="text-center font-semibold text-[30px]  mt-10 mb-10">Solutions</h2>
        <ul className="text-justify mt-10 px-10 md:px-44 list-disc list-inside">
        <li>By sharing the interests generated by the deposits of all the participants, no one looses money, but it is still possible to gamble and have fun. There is a real social impact with the InterPool project.</li><br />
        <li>Sport prediction games, especially with the World Cup around the corner, are incredibly popular. We believe this popular topic can onboard plenty of newcomers that might be interested to dig more about the blockchain. NFT brought plenty of new comers, Sport Predictions games with no losers might also participates to it.</li>
        </ul>
        <h2 className="text-center font-semibold text-[30px]  mt-10 mb-10">Genesis</h2>
        <p className="text-justify mt-10  px-10 md:px-44">Our main inspiration was <Link className="underline " href="https://pooltogether.com/" target="_blank" rel="noopener noreferrer">PoolTogether</Link> which is a Lottery with no loser. We love the no-loss concept, and we wanted to replace the chance factor by the merit factor.<br /> 
        We believe a game was a perfect way to do so, and especially a prediction game, as there is no possibility to cheat, preventing this way sybil attacks.<br /><br /></p>
        <Link href="https://interpool.app" target="_blank" rel="noopener noreferrer" className="mt-10 flex justify-center items-center opacity-80 hover:opacity-100">
        <div className="">
            <Image
            className="rounded-lg"
            src="/interpool-screenshot.png"
            alt="InterPool"
            width={800}
            height={800}
          />   
        </div>        
        </Link>        
        <h2 className="text-center font-semibold text-[30px]  mt-10 mb-10">Pitch Deck ( <a className="text-white underline hover:opacity-80" target="_blank" rel="noopener noreferrer" href="https://www.canva.com/design/DAFYkoIpw5Q/LTvXIvv7xFvqi14DvyVAEA/view?utm_content=DAFYkoIpw5Q&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton">Online</a> / <a className="text-white underline hover:opacity-80" target="_blank" rel="noopener noreferrer" href="https://drive.google.com/uc?id=10nzu64hp-tL2sqpu6VbwkipTGU7HWxF7&export=download">Download</a> )</h2>
        <h2 className="text-center font-semibold text-[30px]  mt-10 mb-10"><Link className="text-white underline hover:opacity-90" href="https://interpool.app" target="_blank" rel="noopener noreferrer">www.interpool.app</Link></h2>
        
    </>
)

export default Interpool;